name: "Website Deploy"

on:
  push:
    branches: ['master', 'release']

jobs:
  jekyll:
    name: "Jekyll"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set S3 bucket
        shell: bash
        run: |
            if [[ "$GITHUB_REF" == "refs/heads/master" ]]
            then
                echo "S3_BUCKET=p2pu-staging" >> $GITHUB_ENV
            elif [[ "$GITHUB_REF" == "refs/heads/release" ]]
            then
                echo "S3_BUCKET=p2pu-website" >> $GITHUB_ENV
            fi

      - run: echo $S3_BUCKET

      - name: build docker image for building jekyll site
        run: docker build . -t local/p2pu-website

      - name: setup config
        run: 'echo mapbox_access_token: "$MAPBOX_ACCESS_TOKEN" > ./_production.yml'
        shell: bash
        env:
          MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_ACCESS_TOKEN}}

      - name: get live data for teams
        run: curl https://learningcircles.p2pu.org/api/teams/ -o ./_data/teams.json

      - name: process live data for teams
        run: cat ./_data/teams.json | python3 _deploy/team_pages.py

      - name: build frontend
        run: docker run --rm --volume `pwd`:/opt/app --workdir /opt/app node:12-buster-slim /bin/sh -c "npm install && npm run build"

      - name: build jekyll site
        run: docker run -v `pwd`:/opt/app -v `pwd`/_site:/opt/app/_site local/p2pu-website jekyll build --future --config _config.yml,_production.yml

      - name: test setup
        run: docker run --name=site -d --volume `pwd`/_site:/var/www node:12-buster-slim /bin/sh -c "npm i serve && npx serve /var/www"

      - name: run test
        run: docker run --rm --link site --volume `pwd`:/opt/app --workdir /opt/app -e TEST_SERVER_URL=http://site:5000 p2pu/puppeteer-docker /bin/sh -c "npm install --only=dev && npm run test"

      - run: 'aws s3 sync ./_site/ s3://$S3_BUCKET/ --delete --storage-class REDUCED_REDUNDANCY --acl public-read'
        shell: bash
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: ./_deploy/s3_redirects.sh
        shell: bash
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: aws s3api put-bucket-website --bucket $S3_BUCKET --website-configuration file://_deploy/s3_website_config.json
        shell: bash
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_PAGER: ""

      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        if: env.S3_BUCKET == 'p2pu-website'
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_PAGER: ""

      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_STAGING --paths "/*"
        if: endsWith(github.ref, '/master')
        env:
          CLOUDFRONT_DISTRIBUTION_ID_STAGING: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING}}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_PAGER: ""
